// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrpc9VPU5Eou_y0YlErKwLpPcgDADund8',
    appId: '1:208046169825:web:8597aeba6eb2d1c5a0e1a0',
    messagingSenderId: '208046169825',
    projectId: 'signinnews',
    authDomain: 'signinnews.firebaseapp.com',
    storageBucket: 'signinnews.appspot.com',
    measurementId: 'G-402YMFY565',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcfxBrmeIlyptt57uuFNgsyUx7FXEMLu8',
    appId: '1:208046169825:android:385d8215ecb20a0ca0e1a0',
    messagingSenderId: '208046169825',
    projectId: 'signinnews',
    storageBucket: 'signinnews.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd7cKVBm6JJzXsSSsue0LpYpcS_1MY6zg',
    appId: '1:208046169825:ios:c2647c00d63a8792a0e1a0',
    messagingSenderId: '208046169825',
    projectId: 'signinnews',
    storageBucket: 'signinnews.appspot.com',
    iosClientId: '208046169825-6e34gtim9qkhm9m0dhj3q4ltloqf5jio.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsAppKellton',
  );
}
